const SHOW_SNACKBAR_MESSAGE = "SHOW_SNACKBAR_MESSAGE"
const HIDE_SNACKBAR_MESSAGE = "HIDE_SNACKBAR_MESSAGE"
const SET_CURRENCY = "SET_CURRENCY"
const SET_CURRENCY_RATES = "SET_CURRENCY_RATES"


export { 
    SHOW_SNACKBAR_MESSAGE, 
    HIDE_SNACKBAR_MESSAGE,
    SET_CURRENCY,
    SET_CURRENCY_RATES
}