const SET_CARS = "SET_CARS"
const TOGGLE_CAR_SEARCH_LOADER = "TOGGLE_CAR_SEARCH_LOADER"
const SET_SEARCH_RESULT = "SET_SEARCH_RESULT"
const RESET_SEARCH_RESULT = "RESET_SEARCH_RESULT"


export { 
    SET_CARS, 
    TOGGLE_CAR_SEARCH_LOADER,
    SET_SEARCH_RESULT,
    RESET_SEARCH_RESULT
}